# Generated by Django 2.0.2 on 2020-01-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Eshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tw_url', models.URLField(blank=True, null=True)),
                ('px_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kanmusu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ichinin', models.CharField(max_length=200)),
                ('Fsutairu', models.CharField(max_length=200)),
                ('tokuchou', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kansyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_gunkan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oogata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=200)),
                ('kansyu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kansyu')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Seiyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seiyu_url', models.URLField(blank=True, null=True)),
                ('seiyu_syozoku', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='kanmusu',
            name='OOgata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Oogata'),
        ),
        migrations.AddField(
            model_name='kanmusu',
            name='eshi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Eshi'),
        ),
        migrations.AddField(
            model_name='kanmusu',
            name='seiyu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Seiyu'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
