# Generated by Django 2.0.2 on 2020-01-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanmusu',
            name='kansyu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Kansyu'),
            preserve_default=False,
        ),
    ]
