# Generated by Django 2.0.2 on 2020-01-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanka_kanmusu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanmusu_name', models.CharField(max_length=200)),
                ('battle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Battle')),
            ],
        ),
    ]
