# Generated by Django 2.0.2 on 2020-02-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_kansyu_setumei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanka_kanmusu',
            old_name='battle_name',
            new_name='battle',
        ),
        migrations.RemoveField(
            model_name='sanka_kanmusu',
            name='kanmusu_name',
        ),
        migrations.AddField(
            model_name='sanka_kanmusu',
            name='kanmusu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Kanmusu'),
            preserve_default=False,
        ),
    ]
