# Generated by Django 2.0.2 on 2020-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200205_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='kansyu',
            name='setumei',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
