# Generated by Django 2.0.2 on 2020-02-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200206_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokkokanmusu',
            old_name='kanmusu',
            new_name='tokkou_kanmusu',
        ),
    ]
