# Generated by Django 2.0.2 on 2020-02-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200206_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokkokanmusu',
            old_name='tokkou_kanmusu',
            new_name='kanmusu',
        ),
    ]
