# Generated by Django 2.0.2 on 2020-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200206_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanmusu',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
