# Generated by Django 2.0.2 on 2020-03-11 13:41

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200226_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playnikki',
            name='nikki',
            field=markdownx.models.MarkdownxField(max_length=2000),
        ),
    ]
