# Generated by Django 2.0.2 on 2020-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_playnikki_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='playnikki',
            name='tag',
            field=models.ManyToManyField(blank=True, to='polls.Tag', verbose_name='タグ'),
        ),
    ]
