# Generated by Django 2.0.2 on 2020-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200409_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='playquestion',
            name='tag',
            field=models.ManyToManyField(blank=True, to='polls.Tag', verbose_name='タグ'),
        ),
    ]
