# Generated by Django 2.0.2 on 2020-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_playquestion_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
