# Generated by Django 2.0.2 on 2020-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_playquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playquestion',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
