# Generated by Django 2.0.2 on 2020-04-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_playquestion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playquestion',
            name='name',
        ),
        migrations.AddField(
            model_name='playquestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
