# Generated by Django 2.0.2 on 2020-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200416_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='answer',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
