# Generated by Django 2.0.2 on 2020-04-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0027_auto_20200418_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='kannmusu_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='kanmusu',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kannmusu_like',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kanmusu'),
        ),
        migrations.AddField(
            model_name='kannmusu_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kannmusu_like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
