# Generated by Django 2.0.2 on 2020-04-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200424_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanmusu',
            name='ninki',
        ),
    ]
