# Generated by Django 2.0.2 on 2020-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_remove_kanmusu_ninki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=100)),
                ('jyusyo', models.CharField(max_length=100)),
                ('kanmusu', models.ManyToManyField(blank=True, to='polls.Kanmusu')),
            ],
        ),
    ]
