# Generated by Django 2.0.2 on 2020-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='ido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='keido',
            field=models.IntegerField(default=0),
        ),
    ]
