# Generated by Django 2.0.2 on 2020-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20200607_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='ido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='map',
            name='keido',
            field=models.CharField(max_length=100),
        ),
    ]
