# Generated by Django 2.0.2 on 2020-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20200608_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='naiyo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='ido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='keido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
